// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = process.env.VITE_SUPABASE_URL || "https://cvxageyyiyyccuqcgbgu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = process.env.VITE_SUPABASE_KEY || "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImN2eGFnZXl5aXl5Y2N1cWNnYmd1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTk3NTI2NzMsImV4cCI6MjA3NTMyODY3M30.RWQseJ58Cz3s6_zud2S1jp4Mx_sGcmwHgkFE697q5j0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});